version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:5.0
    container_name: job-portal-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - job-portal-network

  # Node.js backend service
  backend:
    build: .
    container_name: job-portal-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://admin:password@mongodb:27017/jobportal?authSource=admin
      - JWT_SECRET=OOWXecUkC+PQfksoXBVVQBgJsaNBO8EF/fEbLiwbpP8=
      - PORT=5000
      - LOG_LEVEL=info
      - LOG_DIR=/app/logs
      - CLIENT_URL=http://localhost:5173
    volumes:
      - ./logs:/app/logs
    depends_on:
      - mongodb
    networks:
      - job-portal-network

volumes:
  mongodb_data:

networks:
  job-portal-network:
    driver: bridge